Fix trunk RPC handlers
sapcc/networking-aci pull request #55
Opened 2023-03-13 17:54 UTC by velp

In these two commits:
https://github.com/sapcc/neutron/commit/129b823a8b610284ff95cc5e7b2f7b6ed3540172
https://github.com/sapcc/neutron/commit/69ef824069c3b1435a50c0d937ad45a23ff07c1b
the RPC was changed to use DBEventPayload from the neutron library instead of custom objects.

The new payload has different formats for different event types, here documentation: https://docs.openstack.org/neutron-lib/latest/contributor/callbacks.html#event-objects-dbeventpayload

In this PR we change our driver to have the correct handlers for RPC events coming from Neutron server.

2023-03-13 20:25 UTC, notandy requested changes

2023-03-13 20:25 UTC, notandy commented on networking_aci/plugins/ml2/drivers/mech_aci/trunk.py
> +            current_state == payload.states[0]
I assume it should be a `=`, not `==`:

```
Callback networking_aci.plugins.ml2.drivers.mech_aci.trunk.ACITrunkDriver.trunk_check_valid-1725966 failed with "local variable 'current_state' referenced before assignment"
```

2023-03-13 20:40 UTC, velp commented on networking_aci/plugins/ml2/drivers/mech_aci/trunk.py
> +            current_state == payload.states[0]
ofc, thx

2023-03-14 12:22 UTC, notandy approved these changes
Just tested it, lgtm

2023-03-14 20:54 UTC, merged